
/* Drop Tables

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
 */



/* Create Tables */

CREATE TABLE BOARD
(
	NO number NOT NULL,
	ID varchar2(10) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (NO)
);


CREATE TABLE MEMBER
(
	ID varchar2(10) NOT NULL,
	PASSWORD varchar2(10) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	GENDER nvarchar2(10) NOT NULL,
	INTER nvarchar2(10) NOT NULL,
	GRADE nvarchar2(10) NOT NULL,
	SELF nvarchar2(2000) NOT NULL,
	JOINDATE date DEFAULT SYSDATE,
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;

CREATE SEQUENCE SEQ_BOARD
NOCACHE
NOCYCLE;



